// Code generated by lister-gen. DO NOT EDIT.

package internalversion

import (
	machine "github.com/gardener/machine-controller-manager/pkg/apis/machine"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KubeVirtMachineClassLister helps list KubeVirtMachineClasses.
type KubeVirtMachineClassLister interface {
	// List lists all KubeVirtMachineClasses in the indexer.
	List(selector labels.Selector) (ret []*machine.KubeVirtMachineClass, err error)
	// KubeVirtMachineClasses returns an object that can list and get KubeVirtMachineClasses.
	KubeVirtMachineClasses(namespace string) KubeVirtMachineClassNamespaceLister
	KubeVirtMachineClassListerExpansion
}

// kubeVirtMachineClassLister implements the KubeVirtMachineClassLister interface.
type kubeVirtMachineClassLister struct {
	indexer cache.Indexer
}

// NewKubeVirtMachineClassLister returns a new KubeVirtMachineClassLister.
func NewKubeVirtMachineClassLister(indexer cache.Indexer) KubeVirtMachineClassLister {
	return &kubeVirtMachineClassLister{indexer: indexer}
}

// List lists all KubeVirtMachineClasses in the indexer.
func (s *kubeVirtMachineClassLister) List(selector labels.Selector) (ret []*machine.KubeVirtMachineClass, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*machine.KubeVirtMachineClass))
	})
	return ret, err
}

// KubeVirtMachineClasses returns an object that can list and get KubeVirtMachineClasses.
func (s *kubeVirtMachineClassLister) KubeVirtMachineClasses(namespace string) KubeVirtMachineClassNamespaceLister {
	return kubeVirtMachineClassNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// KubeVirtMachineClassNamespaceLister helps list and get KubeVirtMachineClasses.
type KubeVirtMachineClassNamespaceLister interface {
	// List lists all KubeVirtMachineClasses in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*machine.KubeVirtMachineClass, err error)
	// Get retrieves the KubeVirtMachineClass from the indexer for a given namespace and name.
	Get(name string) (*machine.KubeVirtMachineClass, error)
	KubeVirtMachineClassNamespaceListerExpansion
}

// kubeVirtMachineClassNamespaceLister implements the KubeVirtMachineClassNamespaceLister
// interface.
type kubeVirtMachineClassNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all KubeVirtMachineClasses in the indexer for a given namespace.
func (s kubeVirtMachineClassNamespaceLister) List(selector labels.Selector) (ret []*machine.KubeVirtMachineClass, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*machine.KubeVirtMachineClass))
	})
	return ret, err
}

// Get retrieves the KubeVirtMachineClass from the indexer for a given namespace and name.
func (s kubeVirtMachineClassNamespaceLister) Get(name string) (*machine.KubeVirtMachineClass, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(machine.Resource("kubevirtmachineclass"), name)
	}
	return obj.(*machine.KubeVirtMachineClass), nil
}
