# Sample KubeVirt machine class

apiVersion: machine.sapcloud.io/v1alpha1
kind: KubeVirtMachineClass
metadata:
  name: test-kubevirt # Name of KubeVirt machine class goes here
  namespace: default # Namespace in which the machine class is to be deployed
spec:
  imageName: <image_name> # Machine image name
  memory: <memory> # Memory size of machine
  cores: <cores> # Number of CPU coress for machine
  podNetworkCidr: <pod_network_cidr> # CIDR of the overlay Calico IP pool
  # KubeVirt machine metadata block
  # Be aware, that tags in KubeVirt are translated to
  tags:
    kubernetes.io-cluster-YOUR_CLUSTER_NAME: "1" # This is mandatory as the safety controller uses this tag to identify VMs created by this controller.
    kubernetes.io-role-YOUR_ROLE_NAME: "1" # This is mandatory as the safety controller uses this tag to identify VMs created by this controller.
    tag1: tag1-value # A set of additional tags attached to a machine (optional)
    tag2: tag2-value # A set of additional tags attached to a machine (optional)
  secretRef: # Secret pointing to a secret which contains the provider secret and cloudconfig
    namespace: default  # Namespace
    name: test-secret # Name of the secret