// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	machine "github.com/gardener/machine-controller-manager/pkg/apis/machine"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKubeVirtMachineClasses implements KubeVirtMachineClassInterface
type FakeKubeVirtMachineClasses struct {
	Fake *FakeMachine
	ns   string
}

var kubevirtmachineclassesResource = schema.GroupVersionResource{Group: "machine.sapcloud.io", Version: "", Resource: "kubevirtmachineclasses"}

var kubevirtmachineclassesKind = schema.GroupVersionKind{Group: "machine.sapcloud.io", Version: "", Kind: "KubeVirtMachineClass"}

// Get takes name of the kubeVirtMachineClass, and returns the corresponding kubeVirtMachineClass object, and an error if there is any.
func (c *FakeKubeVirtMachineClasses) Get(name string, options v1.GetOptions) (result *machine.KubeVirtMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kubevirtmachineclassesResource, c.ns, name), &machine.KubeVirtMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.KubeVirtMachineClass), err
}

// List takes label and field selectors, and returns the list of KubeVirtMachineClasses that match those selectors.
func (c *FakeKubeVirtMachineClasses) List(opts v1.ListOptions) (result *machine.KubeVirtMachineClassList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kubevirtmachineclassesResource, kubevirtmachineclassesKind, c.ns, opts), &machine.KubeVirtMachineClassList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &machine.KubeVirtMachineClassList{ListMeta: obj.(*machine.KubeVirtMachineClassList).ListMeta}
	for _, item := range obj.(*machine.KubeVirtMachineClassList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kubeVirtMachineClasses.
func (c *FakeKubeVirtMachineClasses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kubevirtmachineclassesResource, c.ns, opts))

}

// Create takes the representation of a kubeVirtMachineClass and creates it.  Returns the server's representation of the kubeVirtMachineClass, and an error, if there is any.
func (c *FakeKubeVirtMachineClasses) Create(kubeVirtMachineClass *machine.KubeVirtMachineClass) (result *machine.KubeVirtMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kubevirtmachineclassesResource, c.ns, kubeVirtMachineClass), &machine.KubeVirtMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.KubeVirtMachineClass), err
}

// Update takes the representation of a kubeVirtMachineClass and updates it. Returns the server's representation of the kubeVirtMachineClass, and an error, if there is any.
func (c *FakeKubeVirtMachineClasses) Update(kubeVirtMachineClass *machine.KubeVirtMachineClass) (result *machine.KubeVirtMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kubevirtmachineclassesResource, c.ns, kubeVirtMachineClass), &machine.KubeVirtMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.KubeVirtMachineClass), err
}

// Delete takes name of the kubeVirtMachineClass and deletes it. Returns an error if one occurs.
func (c *FakeKubeVirtMachineClasses) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kubevirtmachineclassesResource, c.ns, name), &machine.KubeVirtMachineClass{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKubeVirtMachineClasses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kubevirtmachineclassesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &machine.KubeVirtMachineClassList{})
	return err
}

// Patch applies the patch and returns the patched kubeVirtMachineClass.
func (c *FakeKubeVirtMachineClasses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *machine.KubeVirtMachineClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kubevirtmachineclassesResource, c.ns, name, data, subresources...), &machine.KubeVirtMachineClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*machine.KubeVirtMachineClass), err
}
